export const MOCK_CHALLENGES = [
  {
    id: "1",
    name: "Phase 1 - $50K Challenge",
    price: 399,
    status: "bought",
    accountSize: 50000,
    profitTarget: 4000,
    maxLoss: 5000,
    maxDailyLoss: 2500,
    minTradingDays: 5,
    rules: [
      "Maximum Daily Loss is 5%",
      "Maximum Overall Loss is 10%",
      "Profit Target is 8%",
      "Minimum 5 Trading Days",
      "No Weekend Holding",
    ],
  },
  {
    id: "2",
    name: "Phase 1 - $100K Challenge",
    price: 549,
    status: "available",
    accountSize: 100000,
    profitTarget: 8000,
    maxLoss: 10000,
    maxDailyLoss: 5000,
    minTradingDays: 5,
    rules: [
      "Maximum Daily Loss is 5%",
      "Maximum Overall Loss is 10%",
      "Profit Target is 8%",
      "Minimum 5 Trading Days",
      "News Trading Allowed",
    ],
  },
  {
    id: "3",
    name: "Phase 1 - $200K Challenge",
    price: 999,
    status: "available",
    accountSize: 200000,
    profitTarget: 16000,
    maxLoss: 20000,
    maxDailyLoss: 10000,
    minTradingDays: 5,
    rules: [
      "Maximum Daily Loss is 5%",
      "Maximum Overall Loss is 10%",
      "Profit Target is 8%",
      "Minimum 5 Trading Days",
      "Expert Advisors (EAs) Allowed",
    ],
  },
];

export const MOCK_PERFORMANCE = {
  pastTrades: [
    { date: "2026-04-20", profit: 120, pair: "EUR/USD", type: "Buy" },
    { date: "2026-04-21", profit: -45, pair: "GBP/USD", type: "Sell" },
    { date: "2026-04-22", profit: 210, pair: "XAU/USD", type: "Buy" },
    { date: "2026-04-23", profit: -80, pair: "USD/JPY", type: "Buy" },
    { date: "2026-04-24", profit: 340, pair: "EUR/USD", type: "Sell" },
    { date: "2026-04-25", profit: 150, pair: "GBP/JPY", type: "Buy" },
    { date: "2026-04-26", profit: 80, pair: "XAU/USD", type: "Sell" },
  ],
  currentEquity: 50775,
  startingBalance: 50000,
  winRate: "65%",
  profitFactor: 1.8,
  daysTraded: 7,
};
